services:
  tickets-web:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: tickets-interface
    ports:
      - "8080:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
    restart: unless-stopped